const constants = {
    ADD_DAY:"ADD_DAY",
    REMOVE_DAY:"REMOVE_DAY",
    SET_GOAL:"SET_GOAL",
    ADD_ERROR:"ADD_ERROR",
    CLEAR_ERROR:"CLEAR_ERROR",
    FETRCH_RESORT_NAMES:"FETRCH_RESORT_NAMES",
    CANCEL_FETCHING:"CANCEL_FETCHING",
    CHANGE_SUGGESTIONS:"CHANGE_SUGGESTIONS",
    CLEAR_SEUGGESTIONS:"CLEAR_SEUGGESTIONS"
}

export default constants;